### PR TITLE
Add oobabooga text generation webui api completer

### LINKED ISSUE #11: Local LLM models
Would you consider using a local LLM model that is compatible to the OpenAI GPT API, but would need a config to use locally. 

As information here is an API that is able to be used by a lot of models. 
https://github.com/go-skynet/LocalAI

For embeddings support this is new (https://github.com/go-skynet/LocalAI/issues/70)

### PR DESCRIPTION
**Pull request by kabachuha**
Connects to local models: LLaMa (including llama.cpp), local GPT-derivatives via oobabooga's text generation webui

Closes #11

### CODE REVIEW

**Comment by rizerphe** [comment]
Just opened [this](https://github.com/oobabooga/text-generation-webui/issues/2717); will see what I can do in the meantime

**Comment by kabachuha** [comment]
Yes, thanks! @rizerphe . It was a real problem

**Comment by rizerphe** [comment]
Just opened [this](https://github.com/oobabooga/text-generation-webui/pull/2718) as well; currently working under the assumption that my changes get accepted

**Comment by rizerphe** [comment]
Overall this seems to be working for me; I hope the generation web UI gets CORS support; other than that the only real problem left seems to be model switching - I don't like the idea of it in general, and I don't like how clumsily I had to do it even more.

Oobabooga only allows you to have one model loaded at a time, and switching takes a lot of time, and this isn't too convenient. For now, what I do is before every generate call, I check which model is loaded (through another API call) and load the one I need if necessary. Doing it differently could be smarter but requires a bit of a rewrite.

**Comment by rizerphe** [comment]
Quickly wanted to mention that oobabooga merged my pull request, therefore you don't need to use my fork anymore.

**Pull request merged**
